modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"

license="${mod_license}"

issueTrackerURL="https://github.com/perxenic-studios/Dynamic-Block-Variants/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

displayURL= "https://www.perxenic.dev/dbvariants"

# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" #optional

authors="Auseawesome"

description='''
A mod that adds dynamically generated variants for many blocks
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
